development: "sqlite://dev.db"

local:
        adapter: postgres
        host: localhost
        user: edenzik
        password:
        port: 5432
        database: postgres

deploy:
        adapter: postgres
        host: ec2-107-22-253-198.compute-1.amazonaws.com 
        user: iyqmrjwllheyvy
        password: 68t2Sk9xEw4CsfDRE2g_N6uz9C
        port: 5432
        database: dd05tn6063hgsb

