development: "sqlite://dev.db"

local:
        adapter: postgres
        host: localhost
        user: edenzik
        password:
        port: 5432
        database: postgres

deploy:
        adapter: postgres
        host: ec2-23-23-215-150.compute-1.amazonaws.com
        user: ipjvdnhtwczgqn
        password: aN4EcwY57QUjizDCsG1SmXNG8r
        port: 5432
        database: d4na891quqasmo

